spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/airport_db
    username: Airport
    password: Mushroom
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.web: DEBUG
    com.example.Airport: DEBUG
    org.hibernate.SQL: DEBUG