spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/airport_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework: DEBUG
    com.example: DEBUG
    org.hibernate.SQL: DEBUG

cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:5173